api/urls.py
from django.urls import path, re_path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView, TokenViewBase
from . import views

app_name = 'api'

urlpatterns = [
    re_path(r'^users/token/$', TokenObtainPairView.as_view(), name="get_token"),
    re_path(r'^users/token/refresh/$', views.AutoTokenRefreshView.as_view(), name="refresh_token"),
    re_path(r'^users/token/verify/$', TokenVerifyView.as_view()),

    re_path(r'^users/public/$', views.UsersPublicAPI.as_view(),  name="public_users"),
    re_path(r'^users/public/filter/$', views.UsersPublicFilterAPI.as_view(),  name="public_users_filter"),

    re_path(r'^users/$', views.UsersAPI.as_view(),  name="users"),
    re_path(r'^users/filter/$', views.UsersFilterAPI.as_view(),  name="users_filter"),
    re_path(r'^users/([0-9]+)/$', views.UsersAPI.as_view(),  name="users"),
    re_path(r'^user/register/$', views.UserAuth.as_view(), name="users_register"),

    re_path(r'^certificate/$', views.CertificateAPI.as_view(), name="certificate"),
    re_path(r'^certificate/([0-9]+)/$', views.CertificateAPI.as_view(),  name="certificate"),
    re_path(r'^certificate/filter/$', views.CertificateFilterAPI.as_view(),  name="certificate_filter"),
    re_path(r'^certificate/validate/$', views.ValidateCertificateAPI.as_view(), name="validate_certificate"),

    re_path(r'^user_certificate/$', views.CertificateAssignmentAPI.as_view(), name="user_certificate"),
    re_path(r'^user_certificate/([0-9]+)/$', views.CertificateAssignmentAPI.as_view(), name="user_certificate"),
    re_path(r'^user_certificate/filter/$', views.CertificateAssignmentFilterAPI.as_view(), name="user_certificate_filter"),

    path('download_certificate/<int:user_id>/', views.download_certificate, name='download_certificate'),

    re_path(r'^projects/$', views.ProjectAPI.as_view(), name='projects_api'),
    re_path(r'^projects/(?P<pk>\d+)/$', views.ProjectAPI.as_view(), name='project_detail_api'),

    re_path(r'^events/$', views.EventAPI.as_view(), name='events_api'),
    re_path(r'^events/(?P<pk>\d+)/$', views.EventAPI.as_view(), name='event_detail_api'),

    re_path(r'^user_project/$', views.UserProjectAssignmentAPI.as_view(), name='user_project_api'),
    re_path(r'^user_project/(?P<pk>\d+)/$', views.UserProjectAssignmentAPI.as_view(), name='user_project_assignment_detail_api'),

    re_path(r'^user_event/$', views.UserEventAssignmentAPI.as_view(), name='user_event_api'),
    re_path(r'^user_event/(?P<pk>\d+)/$', views.UserEventAssignmentAPI.as_view(), name='user_event_assignment_detail_api'),

    path('send-email/', views.SendEmailView.as_view(), name='send_email'),

    #re_path(r'^users/$', views.users, name="users"),
    #re_path(r'^users/([0-9]+)/$', views.users, name="users"),
    #re_path(r'^user/register/$', views.user_register, name="user_register"),
]

robotic/urls.py
from django.urls import path
from . import views

app_name = 'robotic'

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login_page, name="login"),
    path('signup/', views.signup_page, name="signup"),
    path('logout/', views.logout_page, name="logout"),
    path('account/not-active/', views.account_not_active, name="account_not_active"),
    path('root/', views.root_page, name="root_page"),
    path('root/active/<int:id>/', views.activate_user, name="activate_user"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('robotic.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

robotic/models.py
import os
from random import randint
from django.db import models
from datetime import date
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify


class School(models.Model):
    name = models.CharField(max_length=255)
    phone_contact = models.CharField(max_length=60, null=True)
    phone_number = models.CharField(max_length=15)

class RoboticUser(AbstractUser):
    TEACHER = 'teacher'
    STAFF = 'staff'
    STUDENT = 'student'
    LEVEL_CHOICES = [
        (TEACHER, 'Teacher'),
        (STAFF, 'Staff'),
        (STUDENT, 'Student'),
    ]

    full_name = models.CharField(max_length=255, blank=True)
    mini_bio = models.TextField(blank=True)
    cpf = models.CharField(max_length=11, blank=True, unique=True)
    registration = models.CharField(max_length=11, blank=True, unique=True)
    profile_picture = models.ImageField(blank=True, null=True)
    birth_date = models.DateField(default=date(2000, 1, 1), blank=True, null=True)
    level_access = models.CharField(max_length=20, choices=LEVEL_CHOICES, default=STUDENT)
    sex = models.CharField(max_length=1, blank=True)
    school = models.ForeignKey(School, on_delete=models.CASCADE, blank=True, null=True)
    is_activated_by_admin = models.BooleanField(default=False)


    def save(self, *args, **kwargs):
        if self.is_superuser == True and self.level_access != "teacher":
            self.level_access == "teacher"
        if self.level_access == "teacher":
            self.is_superuser = True
        
        if not self.cpf:
            self.cpf = str(randint(00000000000, 99999999999))
        if not self.registration:
            self.registration = str(randint(00000000000, 99999999999))

       
        # Verifica se há uma nova imagem sendo carregada
        if self.pk and self.profile_picture and not self.profile_picture.name.startswith('profile_pictures/'):
            old_instance = RoboticUser.objects.get(pk=self.pk)
            if old_instance.profile_picture and old_instance.profile_picture != self.profile_picture:
                # Remove a imagem antiga
                old_instance.profile_picture.delete(save=False)

            # Renomeia a nova imagem
            username = slugify(self.username)
            ext = os.path.splitext(self.profile_picture.name)[1]
            ext = ext.replace('.', '')
            new_filename = f"profile_pictures/{username}_profile_picture.{ext}"

            self.profile_picture.name = new_filename
        super(RoboticUser, self).save(*args, **kwargs)

class Phone(models.Model):
    number = models.CharField(max_length=15)
    whatsapp = models.BooleanField()
    user_phone = models.ForeignKey(RoboticUser, on_delete=models.CASCADE)

class Certificate(models.Model):
    name = models.CharField(max_length=255)
    details = models.CharField(max_length=120)
    start_date = models.DateField()
    end_date = models.DateField()
    city = models.CharField(max_length=255, default="Manacapuru")
    hours = models.PositiveSmallIntegerField()
    date = models.DateField(auto_now_add=True, null=True)
    
    def __str__(self):
        return f'{self.name}'

class CertificateAssignment(models.Model):
    user = models.ForeignKey(RoboticUser, on_delete=models.CASCADE)
    certificate = models.ForeignKey(Certificate, on_delete=models.CASCADE)
    key = models.CharField(max_length=255, unique=True, blank=True)
    assignment_date = models.DateField(auto_now_add=True)
    sended = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = f'{randint(10000000, 99999999)}.{randint(1000000, 9999999)}.{randint(100000, 999999)}.{randint(0, 9)}.{randint(1000000000000000000, 9999999999999999999)}'
        super(CertificateAssignment, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.certificate.name} - {self.user.username}'

class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    status = models.CharField(max_length=50, choices=[('active', 'Active'), ('completed', 'Completed')], default='active')

    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateField()
    location = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class UserProjectAssignment(models.Model):
    user = models.ForeignKey(RoboticUser, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    role = models.CharField(max_length=255)
    assignment_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.project.name} - {self.user.username}'

class UserEventAssignment(models.Model):
    user = models.ForeignKey(RoboticUser, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    role = models.CharField(max_length=255)
    assignment_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.event.name} - {self.user.username}'

robotic/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import RoboticUser, Certificate


class CertificateCreateFrom(forms.Form):
    class Meta:
        model = Certificate
        fields = ('name', 'details', 'start_date', 'end_date', 'city', 'hours')


class RoboticLoginForm(forms.Form):
    username = forms.CharField(label="Nome de Usuário")
    password = forms.CharField(label="Senha", max_length=40, widget=forms.PasswordInput())


class RoboticRegisterForm(UserCreationForm):
    LEVEL_CHOICES = [
        ('teacher', 'Professor'),
        ('student', 'Aluno'),
    ]
   
    username = forms.CharField(label='Nome de Usuario:')
    #full_name = forms.CharField(label='Nome Completo:', max_length=200, widget=forms.TextInput())
    #email = forms.CharField(label='Email:', max_length=200, widget=forms.EmailInput())
    #cpf = forms.CharField(label='CPF:', min_length=11, max_length=11, widget=forms.TextInput())
    #registration = forms.CharField(label="Matrícula:", min_length=11, max_length=11, widget=forms.TextInput())
    password1 = forms.CharField(label='Senha:', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirme sua Senha:', widget=forms.PasswordInput)
    level_access = forms.ChoiceField(choices=LEVEL_CHOICES, label='Tipo de Usuário:', widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = RoboticUser
        fields = [
            'username', 
            #'full_name', 
            #'email', 
            #'cpf', 
            #'registration', 
            'password1', 
            'password2',
        ]

class RoboticUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = RoboticUser
        fields = ('username', 'email')

class RoboticUserChangeForm(UserChangeForm):
    class Meta:
        model = RoboticUser
        fields = ('username', 'email')

robotic/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from .models import RoboticUser
from .forms import RoboticLoginForm, RoboticRegisterForm
from django.db.models import Q


def index(request):
    user = request.user

    return render(request, 'robotic/pages/index.html', {
        'page_name': 'Home',
        'user': user,
    })

def account_not_active(request):
    user = request.user
    if user.is_authenticated:
        messages.error(request, 'Sua conta ainda não foi ativada por um administrador!')
        return redirect('robotic:index')

    return render(request, 'robotic/pages/account_not_active.html')


@login_required(login_url='robotic:login_student')
def root_page(request):
    user = request.user
    robotic_user = RoboticUser.objects.get(user=user)

    if not robotic_user.is_active:
        return redirect('robotic:logout')
    if robotic_user.role == "student":
        print(f'\n{robotic_user.role}\n')
        messages.error(request, 'Voce não tem permissão para acessar esta página. Você é Aluno!')
        return redirect('robotic:index')
    user_to_activate = RoboticUser.objects.all().exclude(id=robotic_user.id)
    return render(request, 'robotic/pages/root_page.html', {
        'user_to_activate': user_to_activate,

    })


def activate_user(request, id):
    user = request.user
    robotic_user = RoboticUser.objects.get(user=user)
    print(robotic_user.user.id)
    if not robotic_user.is_active:
        return redirect('robotic:logout')
    if robotic_user.role == "student":
        return JsonResponse({'message': 'You are not authorized to perform this action.'}, status=404)
    robotic_user = get_object_or_404(RoboticUser, id=id)

    print(robotic_user.user.username)

    if robotic_user:
        robotic_user.is_active = not robotic_user.is_active
        robotic_user.save()
        message = 'User has been activated' if robotic_user.is_active else 'User has been deactivated'
        return JsonResponse({'message': message}, status=200)
    else:
        return JsonResponse({'message': 'User not found.'}, status=404)


def login_page(request):
    if request.user.is_authenticated:
        messages.warning(request, 'Você já está logado!')
        return redirect('robotic:index')
    if request.method == 'POST':
        form = RoboticLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, f'Olá {user.username}!')
                    return redirect('robotic:index')
                else:
                    messages.error(request, 'Sua conta ainda não foi ativada por um administrador!')
                    return redirect('robotic:account_not_active')
            else:
                messages.error(request, 'Nome de usuário ou senha inválidos.')
                return redirect('robotic:login')
    else:
        form = RoboticLoginForm()
        return render(request, 'robotic/pages/login_page.html', {
            'form': form,
        })

def signup_page(request):
    if request.user.is_authenticated:
        messages.warning(request, 'Você já está logado!')
        return redirect('robotic:index')
    if request.method == "POST":
        form = RoboticRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            level_access = form.cleaned_data['level_access']
            if password1 != password2:
                return redirect(reverse('chat:signup'))
            form.save()
            return redirect('robotic:index')
        else:
            return redirect('robotic:signup')
    else:
        form = RoboticRegisterForm()
        return render(request, 'robotic/pages/signup_page.html', {
            'form': form,
        })

def logout_page(request):
    logout(request)
    return redirect('robotic:index')

templates/robotic/partials/footer.html
{% load static %}

<footer class=" text-white">
    <div class="container-fluid position-relative py-3">
      <div class="row text-center align-items-center">

        <img src="{% static 'robotic/images/iconEngrenagensFooter.png' %}" class="img-fluid position-absolute top-50 start-0 translate-middle-y" style="width: 7rem; height: auto;">
      <img src="{% static 'robotic/images/iconEngrenagensFooter_2.png' %}" class="img-fluid position-absolute top-50 end-0 translate-middle-y" style="width: 7rem; height: auto;">
        <!-- Imagem à esquerda -->
        <div class="col-md-2"></div>
        
        <!-- Logo centralizada -->
        <div class="col-md-8 mt-5">
          <img src="{% static 'robotic/images/Logotipo versão negativa.png' %}" alt="Logo" class="img-fluid mx-auto d-block" style="width: 18rem;">
        </div>
        
        <!-- Imagem à direita -->
        <div class="col-md-2"></div>
      </div>

      <!-- Informações abaixo da logo e imagens organizadas em colunas -->
      <div class="row mt-3 justify-content-center text-center">
        <div class="col-md-2 col-xl-2">
          <a href="#" class="text-decoration-none">
            <i class="bi bi-instagram fs-3 me-3" style="color: white;"></i>
          </a>
          <a href="#" class="text-decoration-none">
            <i class="bi bi-facebook fs-3 me-3" style="color: white;"></i>
          </a>
          <a href="#" class="text-decoration-none">
            <i class="bi bi-twitter fs-3" style="color: white;"></i>
          </a>
        </div>
      </div>
      
      <div class="row mt-3 justify-content-center text-center">
        <div class="col-md-2 col-xl-2">
          <a href="#" class="text-decoration-none" style="color: white;">POLÍTICA DE PRIVACIDADE</a>
        </div>
        <div class="col-md-2 col-xl-2">
          <a href="#" class="text-decoration-none" style="color: white;">TERMOS DE USO</a>
        </div>
        <div class="col-md-2 col-xl-2">
          <a href="#" class="text-decoration-none" style="color: white;">CENTRAL DE AJUDA</a>
        </div>
        <div class="col-md-2 col-xl-2">
          <a href="#" class="text-decoration-none" style="color: white;">QUEM SOMOS</a>
        </div>
        <div class="col-md-2 col-xl-2">
          <a href="#" class="text-decoration-none" style="color: white;">@2023</a>
        </div>
      </div>
  </footer>

templates/robotic/partials/header.html
{% load static %}
<div>
    <nav class="navbar navbar-expand-lg">
      <a class="navbar-brand" href="{% url 'robotic:index' %}">
        <img src="{% static 'robotic/images/iconMindNegativa.png' %}" alt="Logo" height="40"> 
        <img src="{% static 'robotic/images/txtMindNegativa.png' %}" alt="LogoTxt" height="20">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link " href="{% url 'robotic:index' %}">INÍCIO</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="#">PROJETOS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="#">SOBRE</a>
          </li>

        {% if robotic_user %}
        	{% if robotic_user.role != "student" %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'robotic:root_page' %}">ROOT</a>
                  </li>
        	{% endif %} 
        {% endif %} 

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " href="">{{user.username}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'robotic:logout' %}">LOGOUT</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'robotic:login' %}">LOGIN</a>
          </li>
          {% endif %}
          


        </ul>
      </div>
    </nav>
  </div>

templates/robotic/partials/popup-notification.html
{% load static %}
<link href="{% static 'robotic/css/spop.css' %}" rel="stylesheet">
<!-- Even better, SamallPop is made with scss,
     @import to your style.scss -->
<script src="{% static 'robotic/js/spop.js' %}"></script>

{% for message in messages %}
<script>
    //spop('{{message}} {{message.tags}}');
    spop({
        template: '{{message}}',
        position  : 'bottom-right',
        style: '{{message.tags}}',
        autoclose: 7000,
    });
</script>
{% endfor %}